openapi: 3.0.3
info:
  title: API de Vacunas
  description: API para consultar el historial de vacunas de los usuarios
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Servidor local de desarrollo

paths:
  /vaccines/{documentNumber}:
    get:
      summary: Obtener historial de vacunas por número de documento
      description: Retorna el historial completo de vacunas de un usuario específico
      parameters:
        - name: documentNumber
          in: path
          required: true
          schema:
            type: string
          description: Número de documento del usuario
      responses:
        '200':
          description: Historial de vacunas encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  vaccines:
                    type: array
                    items:
                      $ref: '#/components/schemas/Vaccine'
              x-specmatic-example: examples/ok.json
        '404':
          description: Usuario no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              x-specmatic-example: examples/not_found.json

components:
  schemas:
    User:
      type: object
      properties:
        documentNumber:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string

    Vaccine:
      type: object
      properties:
        name:
          type: string
        doseNumber:
          type: integer
        vaccinationDate:
          type: string
          format: date
        lotNumber:
          type: string
        manufacturer:
          type: string

    Error:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer 
